require:
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - "bin/*"

Style/FrozenStringLiteralComment:
  Enabled: false

RSpec/ContextWording:
  AllowedPatterns:
    - 'とき$'

RSpec/DescribedClass:
  Enabled: false
